# pip requirements file for building sphinx docs (e.g. nbsphinx)
# requirements_file: REQUIREMENTS.txt

# can also specify a conda env file if pip isn't enough, for example:
# conda:
#   file: environment.yml

sphinx:
    configuration: docs/source/conf.py

build:
    image: latest

# Use python 3 for building
python:
  version: 3.6
  setup_py_install: true
  pip_install: false

