#-*- coding: utf-8 -*-
# This file is automatically generated by 'setup.py'
"""
Created on Tue May 14 15:41:19 2019
Modified on 2019-06-04 13:57:30

@author: Youngju Jaden Kim
"""


__all__ = ['__version__']


__version__ = '0.3.1'

